import { Camera, Lens, DroneModel, SensorType } from '../types/hardware'; // Assuming types are defined here

// --- Sensor Sizes (Reference) ---
// While not explicitly exported like in the JS, this mapping is useful
const sensorTypeMap: Record<string, { name: SensorType, cropFactor: number }> = {
    "Medium Format": { name: "Medium Format", cropFactor: 0.79 }, // Example, adjust per camera
    "Full Frame": { name: "Full Frame", cropFactor: 1.0 },
    "APS-C": { name: "APS-C", cropFactor: 1.5 }, // Common average
    "Micro Four Thirds": { name: "Micro Four Thirds", cropFactor: 2.0 },
    "1-inch": { name: "1-inch", cropFactor: 2.7 },
    "1/2-inch": { name: "1/2-inch", cropFactor: 5.6 } // Example
};

// --- Cameras (Based on reference/Context/utils/cameraDatabase.js) ---
export const cameras: Camera[] = [
    // Phase One aerial cameras
    {
        id: "phase-one-ixm-100",
        brand: "Phase One",
        model: "iXM-100",
        sensorType: "Medium Format",
        sensorWidth: 53.4,
        sensorHeight: 40.0,
        imageWidth: 11664, // Corrected based on JS source
        imageHeight: 8750, // Corrected based on JS source
        megapixels: 100,
        compatibleLensMounts: ['PhaseOne-RSM'],
    },
    {
        id: "phase-one-ixm-rs150",
        brand: "Phase One",
        model: "iXM-RS150",
        sensorType: "Medium Format",
        sensorWidth: 53.4,
        sensorHeight: 40.0,
        imageWidth: 14204,
        imageHeight: 10652,
        megapixels: 150,
        compatibleLensMounts: ['PhaseOne-RSM'],
    },
    {
        id: "phase-one-ixm-50",
        brand: "Phase One",
        model: "iXM-50",
        sensorType: "Medium Format",
        sensorWidth: 44.0,
        sensorHeight: 33.0,
        imageWidth: 8280,
        imageHeight: 6208,
        megapixels: 50,
        compatibleLensMounts: ['PhaseOne-RSM'],
    },
    // Added Phase One XF IQ4
    {
        id: "phase-one-xf-iq4",
        brand: "Phase One",
        model: "XF IQ4",
        sensorType: "Medium Format",
        sensorWidth: 53.4,
        sensorHeight: 40.0,
        imageWidth: 14204,
        imageHeight: 10652,
        megapixels: 151.3,
        compatibleLensMounts: ['PhaseOne-RSM'],
    },
    // Hasselblad cameras
    {
        id: "hasselblad-907x",
        brand: "Hasselblad",
        model: "907X",
        sensorType: "Medium Format",
        sensorWidth: 53.4,
        sensorHeight: 40.0,
        imageWidth: 11656,
        imageHeight: 8742,
        megapixels: 102,
        compatibleLensMounts: ['Hasselblad-XCD'],
    },
    {
        id: "hasselblad-x2d-100c",
        brand: "Hasselblad",
        model: "X2D 100C",
        sensorType: "Medium Format",
        sensorWidth: 53.4,
        sensorHeight: 40.0,
        imageWidth: 11656,
        imageHeight: 8742,
        megapixels: 100,
        compatibleLensMounts: ['Hasselblad-XCD'],
    },
    // Sony Alpha cameras
    {
        id: "sony-a7r-iv",
        brand: "Sony",
        model: "Alpha A7R IV",
        sensorType: "Full Frame",
        sensorWidth: 35.7,
        sensorHeight: 23.8,
        imageWidth: 9504,
        imageHeight: 6336,
        megapixels: 61,
        compatibleLensMounts: ['Sony-E'],
    },
    {
        id: "sony-a7r-v",
        brand: "Sony",
        model: "Alpha A7R V",
        sensorType: "Full Frame",
        sensorWidth: 36.0,
        sensorHeight: 24.0,
        imageWidth: 9504,
        imageHeight: 6336,
        megapixels: 61,
        compatibleLensMounts: ['Sony-E'],
    },
    {
        id: "sony-a7-iv",
        brand: "Sony",
        model: "Alpha A7 IV",
        sensorType: "Full Frame",
        sensorWidth: 36.0,
        sensorHeight: 24.0,
        imageWidth: 7008,
        imageHeight: 4672,
        megapixels: 33,
        compatibleLensMounts: ['Sony-E'],
    },
    {
        id: "sony-a7-iii",
        brand: "Sony",
        model: "Alpha A7 III",
        sensorType: "Full Frame",
        sensorWidth: 36.0,
        sensorHeight: 24.0,
        imageWidth: 6000,
        imageHeight: 4000,
        megapixels: 24,
        compatibleLensMounts: ['Sony-E'],
    },
    {
        id: "sony-a7c",
        brand: "Sony",
        model: "Alpha A7C",
        sensorType: "Full Frame",
        sensorWidth: 36.0,
        sensorHeight: 24.0,
        imageWidth: 6000,
        imageHeight: 4000,
        megapixels: 24,
        compatibleLensMounts: ['Sony-E'],
    },
    {
        id: "sony-a7c-r",
        brand: "Sony",
        model: "Alpha A7C R",
        sensorType: "Full Frame",
        sensorWidth: 36.0,
        sensorHeight: 24.0,
        imageWidth: 9504,
        imageHeight: 6336,
        megapixels: 61,
        compatibleLensMounts: ['Sony-E'],
    },
    {
        id: "sony-a7s-iii",
        brand: "Sony",
        model: "Alpha A7S III",
        sensorType: "Full Frame",
        sensorWidth: 36.0,
        sensorHeight: 24.0,
        imageWidth: 4240,
        imageHeight: 2832,
        megapixels: 12,
        compatibleLensMounts: ['Sony-E'],
    },
    {
        id: "sony-a1",
        brand: "Sony",
        model: "Alpha A1",
        sensorType: "Full Frame",
        sensorWidth: 36.0,
        sensorHeight: 24.0,
        imageWidth: 8640,
        imageHeight: 5760,
        megapixels: 50.1,
        compatibleLensMounts: ['Sony-E'],
    },
    {
        id: "sony-a1-ii",
        brand: "Sony",
        model: "Alpha A1 Mark II",
        sensorType: "Full Frame",
        sensorWidth: 36.0,
        sensorHeight: 24.0,
        imageWidth: 8640,
        imageHeight: 5760,
        megapixels: 50,
        compatibleLensMounts: ['Sony-E'],
    },
    {
        id: "sony-a9-iii",
        brand: "Sony",
        model: "Alpha A9 III",
        sensorType: "Full Frame",
        sensorWidth: 36.0,
        sensorHeight: 24.0,
        imageWidth: 6000,
        imageHeight: 4000,
        megapixels: 24,
        compatibleLensMounts: ['Sony-E'],
    },
    {
        id: "sony-fx3",
        brand: "Sony",
        model: "FX3",
        sensorType: "Full Frame",
        sensorWidth: 36.0,
        sensorHeight: 24.0,
        imageWidth: 4240,
        imageHeight: 2832,
        megapixels: 12,
        compatibleLensMounts: ['Sony-E'],
    },
    {
        id: "sony-fx6",
        brand: "Sony",
        model: "FX6",
        sensorType: "Full Frame",
        sensorWidth: 36.0,
        sensorHeight: 24.0,
        imageWidth: 4240,
        imageHeight: 2832,
        megapixels: 12,
        compatibleLensMounts: ['Sony-E'],
    },
    {
        id: "sony-zv-e1",
        brand: "Sony",
        model: "ZV-E1",
        sensorType: "Full Frame",
        sensorWidth: 36.0,
        sensorHeight: 24.0,
        imageWidth: 4240,
        imageHeight: 2832,
        megapixels: 12,
        compatibleLensMounts: ['Sony-E'],
    },
    {
        id: "sony-a6600",
        brand: "Sony",
        model: "Alpha A6600",
        sensorType: "APS-C",
        sensorWidth: 23.5,
        sensorHeight: 15.6,
        imageWidth: 6000,
        imageHeight: 4000,
        megapixels: 24.2,
        compatibleLensMounts: ['Sony-E'],
    },
    {
        id: "sony-a6400",
        brand: "Sony",
        model: "Alpha A6400",
        sensorType: "APS-C",
        sensorWidth: 23.5,
        sensorHeight: 15.6,
        imageWidth: 6000,
        imageHeight: 4000,
        megapixels: 24.2,
        compatibleLensMounts: ['Sony-E'],
    },
    {
        id: "sony-a6700",
        brand: "Sony",
        model: "Alpha A6700",
        sensorType: "APS-C",
        sensorWidth: 23.5,
        sensorHeight: 15.6,
        imageWidth: 6192,
        imageHeight: 4128,
        megapixels: 26,
        compatibleLensMounts: ['Sony-E'],
    },
    // Canon cameras
    {
        id: "canon-eos-r3",
        brand: "Canon",
        model: "EOS R3",
        sensorType: "Full Frame",
        sensorWidth: 36.0,
        sensorHeight: 24.0,
        imageWidth: 6000,
        imageHeight: 4000,
        megapixels: 24,
        compatibleLensMounts: ['Canon-RF'],
    },
    {
        id: "canon-eos-r5",
        brand: "Canon",
        model: "EOS R5",
        sensorType: "Full Frame",
        sensorWidth: 36.0,
        sensorHeight: 24.0,
        imageWidth: 8192,
        imageHeight: 5464,
        megapixels: 44.8,
        compatibleLensMounts: ['Canon-RF'],
    },
    {
        id: "canon-eos-r5-ii",
        brand: "Canon",
        model: "EOS R5 Mark II",
        sensorType: "Full Frame",
        sensorWidth: 36.0,
        sensorHeight: 24.0,
        imageWidth: 9504,
        imageHeight: 6336,
        megapixels: 60.2,
        compatibleLensMounts: ['Canon-RF'],
    },
    {
        id: "canon-eos-r6",
        brand: "Canon",
        model: "EOS R6",
        sensorType: "Full Frame",
        sensorWidth: 36.0,
        sensorHeight: 24.0,
        imageWidth: 5472,
        imageHeight: 3648,
        megapixels: 20,
        compatibleLensMounts: ['Canon-RF'],
    },
    {
        id: "canon-eos-r6-ii",
        brand: "Canon",
        model: "EOS R6 Mark II",
        sensorType: "Full Frame",
        sensorWidth: 36.0,
        sensorHeight: 24.0,
        imageWidth: 6000,
        imageHeight: 4000,
        megapixels: 24,
        compatibleLensMounts: ['Canon-RF'],
    },
    {
        id: "canon-eos-r",
        brand: "Canon",
        model: "EOS R",
        sensorType: "Full Frame",
        sensorWidth: 36.0,
        sensorHeight: 24.0,
        imageWidth: 6720,
        imageHeight: 4480,
        megapixels: 30.1,
        compatibleLensMounts: ['Canon-RF'],
    },
    {
        id: "canon-eos-rp",
        brand: "Canon",
        model: "EOS RP",
        sensorType: "Full Frame",
        sensorWidth: 36.0,
        sensorHeight: 24.0,
        imageWidth: 6240,
        imageHeight: 4160,
        megapixels: 26.2,
        compatibleLensMounts: ['Canon-RF'],
    },
    {
        id: "canon-eos-r8",
        brand: "Canon",
        model: "EOS R8",
        sensorType: "Full Frame",
        sensorWidth: 36.0,
        sensorHeight: 24.0,
        imageWidth: 6000,
        imageHeight: 4000,
        megapixels: 24,
        compatibleLensMounts: ['Canon-RF'],
    },
    {
        id: "canon-eos-r7",
        brand: "Canon",
        model: "EOS R7",
        sensorType: "APS-C",
        sensorWidth: 22.3,
        sensorHeight: 14.9,
        imageWidth: 6960,
        imageHeight: 4640,
        megapixels: 32.5,
        compatibleLensMounts: ['Canon-RF'],
    },
    {
        id: "canon-eos-r10",
        brand: "Canon",
        model: "EOS R10",
        sensorType: "APS-C",
        sensorWidth: 22.3,
        sensorHeight: 14.9,
        imageWidth: 6000,
        imageHeight: 4000,
        megapixels: 24,
        compatibleLensMounts: ['Canon-RF'],
    },
    {
        id: "canon-eos-r50",
        brand: "Canon",
        model: "EOS R50",
        sensorType: "APS-C",
        sensorWidth: 22.3,
        sensorHeight: 14.9,
        imageWidth: 6000,
        imageHeight: 4000,
        megapixels: 24,
        compatibleLensMounts: ['Canon-RF'],
    },
    {
        id: "canon-eos-r100",
        brand: "Canon",
        model: "EOS R100",
        sensorType: "APS-C",
        sensorWidth: 22.3,
        sensorHeight: 14.9,
        imageWidth: 5184,
        imageHeight: 3456,
        megapixels: 18,
        compatibleLensMounts: ['Canon-RF'],
    },
    {
        id: "canon-eos-5d-iv",
        brand: "Canon",
        model: "EOS 5D Mark IV",
        sensorType: "Full Frame",
        sensorWidth: 36.0,
        sensorHeight: 24.0,
        imageWidth: 6720,
        imageHeight: 4480,
        megapixels: 30.1,
        compatibleLensMounts: ['Canon-EF'],
    },
    // Fujifilm cameras
    {
        id: "fujifilm-gfx-100s",
        brand: "Fujifilm",
        model: "GFX 100S",
        sensorType: "Medium Format",
        sensorWidth: 43.8,
        sensorHeight: 32.9,
        imageWidth: 11648,
        imageHeight: 8736,
        megapixels: 102,
        compatibleLensMounts: ['Fujifilm-G'],
    },
    {
        id: "fujifilm-gfx-100",
        brand: "Fujifilm",
        model: "GFX 100",
        sensorType: "Medium Format",
        sensorWidth: 43.8,
        sensorHeight: 32.9,
        imageWidth: 11648,
        imageHeight: 8736,
        megapixels: 101.8,
        compatibleLensMounts: ['Fujifilm-G'],
    },
    {
        id: "fujifilm-gfx-100-ii",
        brand: "Fujifilm",
        model: "GFX 100 II",
        sensorType: "Medium Format",
        sensorWidth: 43.8,
        sensorHeight: 32.9,
        imageWidth: 11648,
        imageHeight: 8736,
        megapixels: 101.8,
        compatibleLensMounts: ['Fujifilm-G'],
    },
    {
        id: "fujifilm-gfx-50s",
        brand: "Fujifilm",
        model: "GFX 50S",
        sensorType: "Medium Format",
        sensorWidth: 43.8,
        sensorHeight: 32.9,
        imageWidth: 8256,
        imageHeight: 6192,
        megapixels: 51.1,
        compatibleLensMounts: ['Fujifilm-G'],
    },
    {
        id: "fujifilm-gfx-50r",
        brand: "Fujifilm",
        model: "GFX 50R",
        sensorType: "Medium Format",
        sensorWidth: 43.8,
        sensorHeight: 32.9,
        imageWidth: 8256,
        imageHeight: 6192,
        megapixels: 51.1,
        compatibleLensMounts: ['Fujifilm-G'],
    },
    {
        id: "fujifilm-gfx-50s-ii",
        brand: "Fujifilm",
        model: "GFX 50S II",
        sensorType: "Medium Format",
        sensorWidth: 43.8,
        sensorHeight: 32.9,
        imageWidth: 8256,
        imageHeight: 6192,
        megapixels: 51.1,
        compatibleLensMounts: ['Fujifilm-G'],
    },
    {
        id: "fujifilm-x-t4",
        brand: "Fujifilm",
        model: "X-T4",
        sensorType: "APS-C",
        sensorWidth: 23.5,
        sensorHeight: 15.6,
        imageWidth: 6240,
        imageHeight: 4160,
        megapixels: 26,
        compatibleLensMounts: ['Fujifilm-X'],
    },
    {
        id: "fujifilm-x-t5",
        brand: "Fujifilm",
        model: "X-T5",
        sensorType: "APS-C",
        sensorWidth: 23.5,
        sensorHeight: 15.6,
        imageWidth: 6864,
        imageHeight: 4576,
        megapixels: 40.2,
        compatibleLensMounts: ['Fujifilm-X'],
    },
    {
        id: "fujifilm-x-h2",
        brand: "Fujifilm",
        model: "X-H2",
        sensorType: "APS-C",
        sensorWidth: 23.5,
        sensorHeight: 15.6,
        imageWidth: 6864,
        imageHeight: 4576,
        megapixels: 40.2,
        compatibleLensMounts: ['Fujifilm-X'],
    },
    {
        id: "fujifilm-x-h2s",
        brand: "Fujifilm",
        model: "X-H2S",
        sensorType: "APS-C",
        sensorWidth: 23.5,
        sensorHeight: 15.6,
        imageWidth: 6240,
        imageHeight: 4160,
        megapixels: 26,
        compatibleLensMounts: ['Fujifilm-X'],
    },
    {
        id: "fujifilm-x-pro3",
        brand: "Fujifilm",
        model: "X-Pro3",
        sensorType: "APS-C",
        sensorWidth: 23.5,
        sensorHeight: 15.6,
        imageWidth: 6240,
        imageHeight: 4160,
        megapixels: 26,
        compatibleLensMounts: ['Fujifilm-X'],
    },
    // DJI Cameras
    {
        id: "dji-mavic-3-pro",
        brand: "DJI",
        model: "Mavic 3 Pro Camera",
        sensorType: "1-inch",
        sensorWidth: 17.3,
        sensorHeight: 13.0,
        imageWidth: 5280,
        imageHeight: 3956,
        megapixels: 20,
        compatibleLensMounts: [],
    },
    {
        id: "dji-phantom-4-pro",
        brand: "DJI",
        model: "Phantom 4 Pro Camera",
        sensorType: "1-inch",
        sensorWidth: 13.2,
        sensorHeight: 8.8,
        imageWidth: 5472,
        imageHeight: 3648,
        megapixels: 20,
        compatibleLensMounts: [],
    },
    {
        id: "dji-mavic-2-pro",
        brand: "DJI",
        model: "Mavic 2 Pro",
        sensorType: "1-inch",
        sensorWidth: 13.2,
        sensorHeight: 8.8,
        imageWidth: 5472,
        imageHeight: 3648,
        megapixels: 20,
        compatibleLensMounts: [],
    },
    {
        id: "dji-mavic-air-2",
        brand: "DJI",
        model: "Mavic Air 2",
        sensorType: "1/2-inch",
        sensorWidth: 6.4,
        sensorHeight: 4.8,
        imageWidth: 8000,
        imageHeight: 6000,
        megapixels: 48,
        compatibleLensMounts: [],
    }
];

// --- Lenses (Based on reference/Context/utils/cameraDatabase.js reading cameraLensData.json) ---
// We need the actual content of cameraLensData.json for a full list.
// Creating placeholder lenses based on usage in HardwareSelection.vue and common mounts.
export const lenses: Lens[] = [
    // Phase One RSM Mount
    {
        id: 'phaseone-rsm-80mm',
        brand: 'Phase One',
        model: 'RSM 80mm f/2.8',
        focalLength: 80,
        maxAperture: 2.8,
        minAperture: 22,
        lensMount: 'PhaseOne-RSM',
    },
    {
        id: 'phaseone-rsm-35mm',
        brand: 'Phase One',
        model: 'RSM 35mm f/5.6',
        focalLength: 35,
        maxAperture: 5.6,
        minAperture: 22,
        lensMount: 'PhaseOne-RSM',
    },
    {
        id: 'phaseone-rsm-50mm',
        brand: 'Phase One',
        model: 'RSM 50mm f/2.8',
        focalLength: 50,
        maxAperture: 2.8,
        minAperture: 22,
        lensMount: 'PhaseOne-RSM',
    },
    {
        id: 'phaseone-rsm-90mm',
        brand: 'Phase One',
        model: 'RSM 90mm f/3.5',
        focalLength: 90,
        maxAperture: 3.5,
        minAperture: 22,
        lensMount: 'PhaseOne-RSM',
    },
    {
        id: 'phaseone-rsm-150mm',
        brand: 'Phase One',
        model: 'RSM 150mm f/3.5',
        focalLength: 150,
        maxAperture: 3.5,
        minAperture: 22,
        lensMount: 'PhaseOne-RSM',
    },
    // Hasselblad XCD Mount
    {
        id: 'hasselblad-xcd-38v',
        brand: 'Hasselblad',
        model: 'XCD 38V f/2.5',
        focalLength: 38,
        maxAperture: 2.5,
        minAperture: 32,
        lensMount: 'Hasselblad-XCD',
    },
    {
        id: 'hasselblad-xcd-55v',
        brand: 'Hasselblad',
        model: 'XCD 55V f/2.5',
        focalLength: 55,
        maxAperture: 2.5,
        minAperture: 32,
        lensMount: 'Hasselblad-XCD',
    },
    {
        id: 'hasselblad-xcd-90v',
        brand: 'Hasselblad',
        model: 'XCD 90V f/2.5',
        focalLength: 90,
        maxAperture: 2.5,
        minAperture: 32,
        lensMount: 'Hasselblad-XCD',
    },
    {
        id: 'hasselblad-xcd-80mm',
        brand: 'Hasselblad',
        model: 'XCD 80mm f/1.9',
        focalLength: 80,
        maxAperture: 1.9,
        minAperture: 32,
        lensMount: 'Hasselblad-XCD',
    },
    // Sony E-Mount
    {
        id: 'sony-e-50mm-f1.8',
        brand: 'Sony',
        model: 'FE 50mm f/1.8',
        focalLength: 50,
        maxAperture: 1.8,
        minAperture: 22,
        lensMount: 'Sony-E',
    },
    {
        id: 'sony-e-24-70mm-f2.8-gm',
        brand: 'Sony',
        model: 'FE 24-70mm f/2.8 GM',
        focalLength: [24, 70],
        maxAperture: 2.8,
        minAperture: 22,
        lensMount: 'Sony-E',
    },
    {
        id: 'sony-e-16-35mm-f4',
        brand: 'Sony',
        model: 'FE 16-35mm f/4 G',
        focalLength: [16, 35],
        maxAperture: 4.0,
        minAperture: 22,
        lensMount: 'Sony-E',
    },
    {
        id: 'sony-fe-20mm-f1.8',
        brand: 'Sony',
        model: 'FE 20mm f/1.8 G',
        focalLength: 20,
        maxAperture: 1.8,
        minAperture: 22,
        lensMount: 'Sony-E',
    },
    {
        id: 'sony-fe-24mm-f1.4',
        brand: 'Sony',
        model: 'FE 24mm f/1.4 GM',
        focalLength: 24,
        maxAperture: 1.4,
        minAperture: 16,
        lensMount: 'Sony-E',
    },
    {
        id: 'sony-fe-35mm-f1.4',
        brand: 'Sony',
        model: 'FE 35mm f/1.4 GM',
        focalLength: 35,
        maxAperture: 1.4,
        minAperture: 16,
        lensMount: 'Sony-E',
    },
    {
        id: 'sony-fe-50mm-f1.2',
        brand: 'Sony',
        model: 'FE 50mm f/1.2 GM',
        focalLength: 50,
        maxAperture: 1.2,
        minAperture: 16,
        lensMount: 'Sony-E',
    },
    {
        id: 'sony-fe-85mm-f1.4',
        brand: 'Sony',
        model: 'FE 85mm f/1.4 GM',
        focalLength: 85,
        maxAperture: 1.4,
        minAperture: 16,
        lensMount: 'Sony-E',
    },
    {
        id: 'sony-fe-85mm-f1.8',
        brand: 'Sony',
        model: 'FE 85mm f/1.8',
        focalLength: 85,
        maxAperture: 1.8,
        minAperture: 22,
        lensMount: 'Sony-E',
    },
    {
        id: 'sony-fe-135mm-f1.8',
        brand: 'Sony',
        model: 'FE 135mm f/1.8 GM',
        focalLength: 135,
        maxAperture: 1.8,
        minAperture: 22,
        lensMount: 'Sony-E',
    },
    // Canon RF Mount
    {
        id: 'canon-rf-16mm-f2.8',
        brand: 'Canon',
        model: 'RF 16mm f/2.8 STM',
        focalLength: 16,
        maxAperture: 2.8,
        minAperture: 22,
        lensMount: 'Canon-RF',
    },
    {
        id: 'canon-rf-24mm-f1.8',
        brand: 'Canon',
        model: 'RF 24mm f/1.8 MACRO IS STM',
        focalLength: 24,
        maxAperture: 1.8,
        minAperture: 22,
        lensMount: 'Canon-RF',
    },
    {
        id: 'canon-rf-35mm-f1.8',
        brand: 'Canon',
        model: 'RF 35mm f/1.8 MACRO IS STM',
        focalLength: 35,
        maxAperture: 1.8,
        minAperture: 22,
        lensMount: 'Canon-RF',
    },
    {
        id: 'canon-rf-50mm-f1.2',
        brand: 'Canon',
        model: 'RF 50mm f/1.2L USM',
        focalLength: 50,
        maxAperture: 1.2,
        minAperture: 16,
        lensMount: 'Canon-RF',
    },
    {
        id: 'canon-rf-50mm-f1.8',
        brand: 'Canon',
        model: 'RF 50mm f/1.8 STM',
        focalLength: 50,
        maxAperture: 1.8,
        minAperture: 22,
        lensMount: 'Canon-RF',
    },
    {
        id: 'canon-rf-85mm-f1.2',
        brand: 'Canon',
        model: 'RF 85mm f/1.2L USM',
        focalLength: 85,
        maxAperture: 1.2,
        minAperture: 16,
        lensMount: 'Canon-RF',
    },
    {
        id: 'canon-rf-85mm-f2',
        brand: 'Canon',
        model: 'RF 85mm f/2 MACRO IS STM',
        focalLength: 85,
        maxAperture: 2,
        minAperture: 22,
        lensMount: 'Canon-RF',
    },
    {
        id: 'canon-rf-100mm-f2.8',
        brand: 'Canon',
        model: 'RF 100mm f/2.8L MACRO IS USM',
        focalLength: 100,
        maxAperture: 2.8,
        minAperture: 32,
        lensMount: 'Canon-RF',
    },
    {
        id: 'canon-rf-135mm-f1.8',
        brand: 'Canon',
        model: 'RF 135mm f/1.8L IS USM',
        focalLength: 135,
        maxAperture: 1.8,
        minAperture: 22,
        lensMount: 'Canon-RF',
    },
    // Canon RF-S Mount (APS-C)
    {
        id: 'canon-rf-s-16mm-f2.8',
        brand: 'Canon',
        model: 'RF-S 16mm F2.8 STM',
        focalLength: 16,
        maxAperture: 2.8,
        minAperture: 22,
        lensMount: 'Canon-RF',
    },
    {
        id: 'canon-rf-s-22mm-f2',
        brand: 'Canon',
        model: 'RF-S 22mm F2 STM',
        focalLength: 22,
        maxAperture: 2,
        minAperture: 22,
        lensMount: 'Canon-RF',
    },
    {
        id: 'canon-rf-s-32mm-f1.4',
        brand: 'Canon',
        model: 'RF-S 32mm F1.4 STM',
        focalLength: 32,
        maxAperture: 1.4,
        minAperture: 16,
        lensMount: 'Canon-RF',
    },
    // Canon EF Mount
    {
        id: 'canon-ef-24mm-f1.4',
        brand: 'Canon',
        model: 'EF 24mm f/1.4L II USM',
        focalLength: 24,
        maxAperture: 1.4,
        minAperture: 22,
        lensMount: 'Canon-EF',
    },
    {
        id: 'canon-ef-35mm-f1.4',
        brand: 'Canon',
        model: 'EF 35mm f/1.4L II USM',
        focalLength: 35,
        maxAperture: 1.4,
        minAperture: 22,
        lensMount: 'Canon-EF',
    },
    {
        id: 'canon-ef-50mm-f1.2',
        brand: 'Canon',
        model: 'EF 50mm f/1.2L USM',
        focalLength: 50,
        maxAperture: 1.2,
        minAperture: 16,
        lensMount: 'Canon-EF',
    },
    {
        id: 'canon-ef-50mm-f1.4',
        brand: 'Canon',
        model: 'EF 50mm f/1.4 USM',
        focalLength: 50,
        maxAperture: 1.4,
        minAperture: 22,
        lensMount: 'Canon-EF',
    },
    {
        id: 'canon-ef-85mm-f1.2',
        brand: 'Canon',
        model: 'EF 85mm f/1.2L II USM',
        focalLength: 85,
        maxAperture: 1.2,
        minAperture: 16,
        lensMount: 'Canon-EF',
    },
    {
        id: 'canon-ef-85mm-f1.4',
        brand: 'Canon',
        model: 'EF 85mm f/1.4L IS USM',
        focalLength: 85,
        maxAperture: 1.4,
        minAperture: 22,
        lensMount: 'Canon-EF',
    },
    {
        id: 'canon-ef-135mm-f2',
        brand: 'Canon',
        model: 'EF 135mm f/2L USM',
        focalLength: 135,
        maxAperture: 2,
        minAperture: 32,
        lensMount: 'Canon-EF',
    },
    {
        id: 'canon-ef-24-70mm-f2.8',
        brand: 'Canon',
        model: 'EF 24-70mm f/2.8L II USM',
        focalLength: [24, 70],
        maxAperture: 2.8,
        minAperture: 22,
        lensMount: 'Canon-EF',
    },
    {
        id: 'canon-ef-70-200mm-f2.8',
        brand: 'Canon',
        model: 'EF 70-200mm f/2.8L IS III USM',
        focalLength: [70, 200],
        maxAperture: 2.8,
        minAperture: 32,
        lensMount: 'Canon-EF',
    },
    {
        id: 'canon-ef-16-35mm-f2.8',
        brand: 'Canon',
        model: 'EF 16-35mm f/2.8L III USM',
        focalLength: [16, 35],
        maxAperture: 2.8,
        minAperture: 22,
        lensMount: 'Canon-EF',
    },
    // Fujifilm G Mount
    {
        id: 'fujifilm-g-gf-110mm-f2',
        brand: 'Fujifilm',
        model: 'GF 110mm f/2 R LM WR',
        focalLength: 110,
        maxAperture: 2.0,
        minAperture: 22,
        lensMount: 'Fujifilm-G',
    },
    {
        id: 'fujifilm-g-gf-23mm-f4',
        brand: 'Fujifilm',
        model: 'GF 23mm f/4 R LM WR',
        focalLength: 23,
        maxAperture: 4.0,
        minAperture: 32,
        lensMount: 'Fujifilm-G',
    },
    {
        id: 'fujifilm-g-gf-30mm-f3.5',
        brand: 'Fujifilm',
        model: 'GF 30mm f/3.5 R WR',
        focalLength: 30,
        maxAperture: 3.5,
        minAperture: 32,
        lensMount: 'Fujifilm-G',
    },
    {
        id: 'fujifilm-g-gf-45mm-f2.8',
        brand: 'Fujifilm',
        model: 'GF 45mm f/2.8 R WR',
        focalLength: 45,
        maxAperture: 2.8,
        minAperture: 32,
        lensMount: 'Fujifilm-G',
    },
    {
        id: 'fujifilm-g-gf-50mm-f3.5',
        brand: 'Fujifilm',
        model: 'GF 50mm f/3.5 R LM WR',
        focalLength: 50,
        maxAperture: 3.5,
        minAperture: 32,
        lensMount: 'Fujifilm-G',
    },
    {
        id: 'fujifilm-g-gf-55mm-f1.7',
        brand: 'Fujifilm',
        model: 'GF 55mm f/1.7 R WR',
        focalLength: 55,
        maxAperture: 1.7,
        minAperture: 22,
        lensMount: 'Fujifilm-G',
    },
    {
        id: 'fujifilm-g-gf-63mm-f2.8',
        brand: 'Fujifilm',
        model: 'GF 63mm f/2.8 R WR',
        focalLength: 63,
        maxAperture: 2.8,
        minAperture: 32,
        lensMount: 'Fujifilm-G',
    },
    {
        id: 'fujifilm-g-gf-80mm-f1.7',
        brand: 'Fujifilm',
        model: 'GF 80mm f/1.7 R WR',
        focalLength: 80,
        maxAperture: 1.7,
        minAperture: 22,
        lensMount: 'Fujifilm-G',
    },
    {
        id: 'fujifilm-g-gf-120mm-f4',
        brand: 'Fujifilm',
        model: 'GF 120mm f/4 Macro R LM OIS WR',
        focalLength: 120,
        maxAperture: 4.0,
        minAperture: 32,
        lensMount: 'Fujifilm-G',
    },
    {
        id: 'fujifilm-g-gf-250mm-f4',
        brand: 'Fujifilm',
        model: 'GF 250mm f/4 R LM OIS WR',
        focalLength: 250,
        maxAperture: 4.0,
        minAperture: 32,
        lensMount: 'Fujifilm-G',
    },
    {
        id: 'fujifilm-g-gf-32-64mm-f4',
        brand: 'Fujifilm',
        model: 'GF 32-64mm f/4 R LM WR',
        focalLength: [32, 64],
        maxAperture: 4.0,
        minAperture: 32,
        lensMount: 'Fujifilm-G',
    },
    {
        id: 'fujifilm-g-gf-45-100mm-f4',
        brand: 'Fujifilm',
        model: 'GF 45-100mm f/4 R LM OIS WR',
        focalLength: [45, 100],
        maxAperture: 4.0,
        minAperture: 32,
        lensMount: 'Fujifilm-G',
    },
    {
        id: 'fujifilm-g-gf-100-200mm-f5.6',
        brand: 'Fujifilm',
        model: 'GF 100-200mm f/5.6 R LM OIS WR',
        focalLength: [100, 200],
        maxAperture: 5.6,
        minAperture: 32,
        lensMount: 'Fujifilm-G',
    },
    // Fujifilm X Mount
    {
        id: 'fujifilm-x-xf-16mm-f1.4',
        brand: 'Fujifilm',
        model: 'XF 16mm f/1.4 R WR',
        focalLength: 16,
        maxAperture: 1.4,
        minAperture: 16,
        lensMount: 'Fujifilm-X',
    },
    {
        id: 'fujifilm-x-xf-23mm-f1.4',
        brand: 'Fujifilm',
        model: 'XF 23mm f/1.4 R LM WR',
        focalLength: 23,
        maxAperture: 1.4,
        minAperture: 16,
        lensMount: 'Fujifilm-X',
    },
    {
        id: 'fujifilm-x-xf-33mm-f1.4',
        brand: 'Fujifilm',
        model: 'XF 33mm f/1.4 R LM WR',
        focalLength: 33,
        maxAperture: 1.4,
        minAperture: 16,
        lensMount: 'Fujifilm-X',
    },
    {
        id: 'fujifilm-x-xf-35mm-f1.4',
        brand: 'Fujifilm',
        model: 'XF 35mm f/1.4 R',
        focalLength: 35,
        maxAperture: 1.4,
        minAperture: 16,
        lensMount: 'Fujifilm-X',
    },
    {
        id: 'fujifilm-x-xf-50mm-f1.0',
        brand: 'Fujifilm',
        model: 'XF 50mm f/1.0 R WR',
        focalLength: 50,
        maxAperture: 1.0,
        minAperture: 16,
        lensMount: 'Fujifilm-X',
    },
    {
        id: 'fujifilm-x-xf-56mm-f1.2',
        brand: 'Fujifilm',
        model: 'XF 56mm f/1.2 R',
        focalLength: 56,
        maxAperture: 1.2,
        minAperture: 16,
        lensMount: 'Fujifilm-X',
    },
    {
        id: 'fujifilm-x-xf-80mm-f2.8',
        brand: 'Fujifilm',
        model: 'XF 80mm f/2.8 R LM OIS WR Macro',
        focalLength: 80,
        maxAperture: 2.8,
        minAperture: 22,
        lensMount: 'Fujifilm-X',
    },
    {
        id: 'fujifilm-x-xf-90mm-f2',
        brand: 'Fujifilm',
        model: 'XF 90mm f/2 R LM WR',
        focalLength: 90,
        maxAperture: 2.0,
        minAperture: 16,
        lensMount: 'Fujifilm-X',
    },
    {
        id: 'fujifilm-x-xf-200mm-f2',
        brand: 'Fujifilm',
        model: 'XF 200mm f/2 R LM OIS WR',
        focalLength: 200,
        maxAperture: 2.0,
        minAperture: 22,
        lensMount: 'Fujifilm-X',
    },
];

// --- Drones (Based on reference/Context/utils/cameraDatabase.js) ---
export const droneModels: DroneModel[] = [
    {
        id: "freefly-astro",
        name: "Freefly Astro",
        brand: "Freefly",
        maxPayload: 1.5,
        compatiblePayloads: ['Sony-a7R-Series', 'MicaSense-RedEdge'],
        imageUrl: '/images/drones/astro-top-view.png'
    },
    {
        id: "freefly-alta-x",
        name: "Freefly Alta X",
        brand: "Freefly",
        maxPayload: 15.9,
        compatiblePayloads: ['PhaseOne-iXM', 'Gimbal-Payloads'],
        imageUrl: '/images/drones/alta-top-view.png'
    },
    // Add DJI Drones (if selectable as separate drones, not just cameras)
    {
        id: "dji-mavic-3-pro-drone",
        name: "DJI Mavic 3 Pro",
        brand: "DJI",
    },
    {
        id: "dji-phantom-4-pro-drone",
        name: "DJI Phantom 4 Pro",
        brand: "DJI",
    },
];

// --- Helper Functions ---

/**
 * Finds a camera by its ID.
 * @param id The ID of the camera to find.
 * @returns The camera object or undefined if not found.
 */
export const getCameraById = (id: string | null | undefined): Camera | undefined => {
    if (!id) return undefined;
    return cameras.find(camera => camera.id === id);
};

/**
 * Finds a lens by its ID.
 * @param id The ID of the lens to find.
 * @returns The lens object or undefined if not found.
 */
export const getLensById = (id: string | null | undefined): Lens | undefined => {
    if (!id) return undefined;
    return lenses.find(lens => lens.id === id);
};

/**
 * Finds a drone model by its ID.
 * @param id The ID of the drone model to find.
 * @returns The drone model object or undefined if not found.
 */
export const getDroneModelById = (id: string | null | undefined): DroneModel | undefined => {
    if (!id) return undefined;
    return droneModels.find(drone => drone.id === id);
};

/**
 * Gets lenses compatible with a given camera based on mount type
 * @param cameraId The ID of the camera
 * @returns An array of compatible lenses
 */
export const getCompatibleLenses = (cameraId: string | null | undefined): Lens[] => {
    const camera = getCameraById(cameraId);
    if (!camera || !camera.compatibleLensMounts || camera.compatibleLensMounts.length === 0) {
        return [];
    }
    
    return lenses.filter(lens => 
        camera.compatibleLensMounts.includes(lens.lensMount)
    );
};

/**
 * Returns an array of common f-stop values within a lens's range
 * @param lens The lens object
 * @returns An array of common f-stop numbers within the lens range
 */
export const getLensFStops = (lens: Lens | undefined): number[] => {
    if (!lens) return [2.8, 4, 5.6, 8, 11, 16, 22]; // Default stops

    const commonStops = [
        1.0, 1.1, 1.2, 1.4, 1.8, 2.0, 2.2, 2.5, 2.8, 3.2, 3.5, 4.0, 
        4.5, 5.0, 5.6, 6.3, 7.1, 8.0, 9.0, 10, 11, 13, 14, 16, 18, 20, 22, 32
    ];
    
    return commonStops.filter(stop => stop >= lens.maxAperture && stop <= lens.minAperture);
}; 